import json
import time
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
import structlog
from pathlib import Path
import yaml

from tools.llama_wrapper import LlamaWrapper
from models.lead import LeadBatch

logger = structlog.get_logger()

class TaskPlan(BaseModel):
    """Task plan generated by orchestrator"""
    search_queries: List[str] = Field(..., description="List of search queries to execute")
    target_fields: List[str] = Field(..., description="Lead fields to prioritize")
    max_results: int = Field(..., description="Maximum number of results to fetch")
    quality_threshold: float = Field(..., description="Minimum quality threshold (0.0-1.0)")
    user_query: Optional[str] = Field(None, description="Original user query")

class OrchestratorAgent:
    """
    Orchestrator agent responsible for task decomposition, routing, and result aggregation.
    Uses LlamaWrapper for LLM operations and maintains shared state in artifacts directory.
    """
    
    def __init__(self, settings_path: str = "config/settings.yaml"):
        """
        Initialize OrchestratorAgent.
        
        Args:
            settings_path: Path to settings YAML file
        """
        self.settings = self._load_settings(settings_path)
        self.llama_wrapper = LlamaWrapper(
            ollama_host=self.settings.get("models", {}).get("ollama_host", "http://localhost:11434")
        )
        self.model_name = self.settings.get("models", {}).get("orchestrator", "gpt-oss:120b-cloud")
        self.artifacts_dir = Path("artifacts")
        self.artifacts_dir.mkdir(exist_ok=True)
        
    async def __aenter__(self):
        """Async context manager entry"""
        return self
        
    async def __aexit__(self, exc_type, exc_val, exc_tb):
        """Async context manager exit"""
        pass
        
    def _load_settings(self, settings_path: str) -> Dict[str, Any]:
        """Load settings from YAML file"""
        try:
            with open(settings_path, 'r') as f:
                return yaml.safe_load(f) or {}
        except Exception as e:
            logger.warning("Failed to load settings", error=str(e), path=settings_path)
            return {}
            
    async def decompose_query(self, user_input: str) -> TaskPlan:
        """
        Decompose user query into actionable task plan.
        
        Args:
            user_input: Natural language user query
            
        Returns:
            TaskPlan with search strategy
        """
        log = logger.bind(user_input=user_input)
        log.info("Decomposing query")
        
        # Load orchestrator prompt
        prompt_path = Path("config/prompts/orchestrator_system.txt")
        if not prompt_path.exists():
            raise FileNotFoundError(f"Orchestrator prompt not found: {prompt_path}")
            
        with open(prompt_path, 'r') as f:
            system_prompt = f.read()
            
        # Create extraction prompt
        extraction_prompt = f"""{system_prompt}

User Query: "{user_input}"

Analyze this query and provide a task plan in JSON format with the following structure:
{{
    "search_queries": ["query1", "query2", ...],
    "target_fields": ["field1", "field2", ...],
    "max_results": number,
    "quality_threshold": float_between_0_and_1
}}

JSON Response:"""
        
        try:
            # Use structured extraction to get TaskPlan
            async with LlamaWrapper(
                ollama_host=self.settings.get("models", {}).get("ollama_host", "http://localhost:11434")
            ) as wrapper:
                task_plan = await wrapper.structured_extract(
                    prompt=extraction_prompt,
                    schema=TaskPlan,
                    model=self.model_name,
                    temperature=0.1,
                    max_tokens=500
                )
                
            # Add original query
            task_plan.user_query = user_input
            
            # Save to artifacts
            self._save_artifact("task_plan", task_plan.model_dump())
            
            log.info("Query decomposition completed", task_plan=task_plan.model_dump())
            return task_plan
                
        except Exception as e:
            log.error("Query decomposition failed", error=str(e))
            raise
            
    def route_task(self, task_status: Dict[str, Any]) -> str:
        """
        Determine next agent based on task status.
        
        Args:
            task_status: Current task status dictionary
            
        Returns:
            Name of next agent to execute
        """
        log = logger.bind(task_status=task_status)
        
        # Determine next agent based on current state
        current_stage = task_status.get("current_stage", "start")
        
        routing_map = {
            "start": "web_navigator",
            "search_complete": "content_extractor",
            "extraction_complete": "lead_enricher",
            "enrichment_complete": "validator",
            "validation_complete": "complete"
        }
        
        next_agent = routing_map.get(current_stage, "web_navigator")
        
        log.info("Task routing decision", current_stage=current_stage, next_agent=next_agent)
        return next_agent
        
    async def aggregate_results(self, agent_outputs: List[Dict[str, Any]]) -> LeadBatch:
        """
        Aggregate results from all agents into final LeadBatch.
        
        Args:
            agent_outputs: List of agent output dictionaries
            
        Returns:
            LeadBatch with aggregated leads and statistics
        """
        log = logger.bind(output_count=len(agent_outputs))
        log.info("Aggregating agent results")
        
        # Collect all validated leads from agent outputs
        all_leads = []
        total_processed = 0
        successful_extractions = 0
        
        for output in agent_outputs:
            if "validated_leads" in output:
                all_leads.extend(output["validated_leads"])
                successful_extractions += len(output["validated_leads"])
            
            if "total_processed" in output:
                total_processed += output["total_processed"]
                
        # Calculate statistics
        success_rate = (successful_extractions / total_processed) if total_processed > 0 else 0.0
        avg_confidence = sum(lead.confidence_score for lead in all_leads) / len(all_leads) if all_leads else 0.0
        
        # Create LeadBatch
        lead_batch = LeadBatch(
            leads=all_leads,
            query="Aggregated from multiple agents",
            metadata={
                "total_processed": total_processed,
                "successful_extractions": successful_extractions,
                "success_rate": success_rate,
                "avg_confidence": avg_confidence,
                "agent_count": len(agent_outputs)
            }
        )
        
        # Save final output
        self._save_artifact("final_output", {
            "lead_batch": lead_batch.model_dump(),
            "statistics": {
                "total_leads": len(all_leads),
                "success_rate": success_rate,
                "avg_confidence": avg_confidence
            }
        })
        
        log.info(
            "Results aggregation completed",
            total_leads=len(all_leads),
            success_rate=success_rate,
            avg_confidence=avg_confidence
        )
        
        return lead_batch
        
    def _save_artifact(self, stage: str, data: Dict[str, Any]):
        """
        Save data to artifacts directory.
        
        Args:
            stage: Stage name (e.g., "task_plan", "final_output")
            data: Data to save
        """
        timestamp = int(time.time())
        filename = f"{stage}_{timestamp}.json"
        filepath = self.artifacts_dir / filename
        
        artifact = {
            "timestamp": timestamp,
            "stage": stage,
            "data": data,
            "metadata": {
                "agent_name": "orchestrator",
                "model_used": self.model_name
            }
        }
        
        try:
            with open(filepath, 'w') as f:
                json.dump(artifact, f, indent=2, default=str)
                
            logger.info("Artifact saved", stage=stage, filepath=str(filepath))
        except Exception as e:
            logger.error("Failed to save artifact", stage=stage, error=str(e))
            
    def get_artifact_path(self, stage: str, timestamp: Optional[int] = None) -> Optional[Path]:
        """
        Get path to artifact file.
        
        Args:
            stage: Stage name
            timestamp: Specific timestamp, or None for latest
            
        Returns:
            Path to artifact file or None if not found
        """
        pattern = f"{stage}_*.json"
        matches = list(self.artifacts_dir.glob(pattern))
        
        if not matches:
            return None
            
        if timestamp:
            # Find specific timestamp
            for match in matches:
                if str(timestamp) in match.name:
                    return match
            return None
        else:
            # Return latest
            return max(matches, key=lambda p: p.stat().st_mtime)